show list film
AT-PHPIntership/booking-ticket pull request #25
Opened 2018-08-01 08:32 UTC by at-namtran

## Description
show list film.
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
List of all queries and attach the result of each explaining query (in text, screenshot...)

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-08-02 07:43 UTC, mvn-khanhnguyen-dn reviewed
LGTM

2018-08-03 03:25 UTC, ghost requested changes

2018-08-03 03:25 UTC, at-huenguyen commented on resources/views/admin/pages/films/index.blade.php
> +          @if ($films)
bỏ `if` đi nha em có `foreach` rồi

2018-08-03 03:25 UTC, at-huenguyen commented on resources/views/admin/pages/films/index.blade.php
> +                  @if ($film->images->count() > 0)
bỏ `if` nha em, có `for` rồi

2018-08-03 03:25 UTC, at-huenguyen commented on resources/views/admin/pages/films/index.blade.php
> +                  @else
em có thể dùng `if` chỗ này
```
@if (!$film->images->count()) {
...
```

2018-08-03 03:25 UTC, at-huenguyen commented on resources/views/admin/pages/films/index.blade.php
> +                  <form class="col-md-4" method="POST" onclick="return confirm('@lang('film.admin.message.msg_del')')"
xử lí js thì bỏ vào js nha em. `onclick` này em bỏ vào file js nhá

2018-08-03 08:32 UTC, ghost approved these changes

2018-08-03 08:32 UTC, merged