[Admin] Admin create user test
AT-PHPIntership/booking-ticket pull request #26
Opened 2018-08-01 17:11 UTC by at-khanhnguyen

## Description
Create test case for admin when create user
## Reference Requirements
- Task ID: TI-1

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
No query
- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-08-03 01:27 UTC, at-namtran commented
LGTM

2018-08-03 08:50 UTC, ghost requested changes

2018-08-03 08:50 UTC, at-huenguyen commented on app/Http/Requests/CreateUserRequest.php
> +            'phone.*' => trans('user.admin.add.message.add_invalid_phone'),
chỗ này em nhập bao nhiêu số điện thoại vại?, sao có `*` ở đây?

2018-08-03 08:50 UTC, at-huenguyen commented on app/Http/Requests/CreateUserRequest.php
> +            'address.*' => trans('user.admin.message.require_address')
nhập nhiều địa chỉ cũng đc à em? sao có `*`?

2018-08-03 09:25 UTC, at-khanhnguyen commented on app/Http/Requests/CreateUserRequest.php
> +            'phone.*' => trans('user.admin.add.message.add_invalid_phone'),
Cái ni em muốn catch hết lỗi liên quan đến phone đều xuất 1 thông báo á chị @at-huenguyen

2018-08-06 06:40 UTC, at-huenguyen commented on tests/Browser/Admin/User/CreateUserTest.php
> +                ->type('full_name', 'Nguyen Huu Khanh')
mấy `full_name`, `email`,..., button submit nữa em có thể khai báo ở `element()` của `CreateUserPage` và dùng lại ở đây đc ko?

2018-08-10 03:18 UTC, ghost approved these changes

2018-08-10 03:18 UTC, merged