[Admin] List schedule in dasboard
AT-PHPIntership/booking-ticket pull request #33
Opened 2018-08-07 02:00 UTC by at-khanhnguyen

## Description
Create layout and list schedule in admin dasboard
## Reference Requirements
- Task ID: TI-1

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
- Query 1:
```sql
explain select `schedules`.`id` as `id`, `rooms`.`status`, `rooms`.`name` as `name`, 
`schedules`.`start_time`, `schedules`.`end_time`, `films`.`name` as `fname`,
 COUNT(booking_details.seat_id) as numSeatBooked from `schedules` inner join `films` on
 `schedules`.`film_id` = `films`.`id` inner join `rooms` on `schedules`.`room_id` = `rooms`.`id` inner join
 `tickets` on `schedules`.`id` = `tickets`.`schedule_id` inner join `booking_details` on `tickets`.`id` =
 `booking_details`.`ticket_id` where `films`.`deleted_at` is null and `schedules`.`deleted_at` is null group
 by `schedule_id` order by `schedules`.`id` asc limit 10 offset 0;
+----+-------------+-----------------+------------+--------+-------------------------------------------------------------+-----------------------------------+---------+----------------------------+------+----------+----------------------------------------------+
| id | select_type | table           | partitions | type   | possible_keys                                               | key                               | key_len | ref                        | rows | filtered | Extra                                        |
+----+-------------+-----------------+------------+--------+-------------------------------------------------------------+-----------------------------------+---------+----------------------------+------+----------+----------------------------------------------+
|  1 | SIMPLE      | tickets         | NULL       | index  | PRIMARY,tickets_schedule_id_foreign                         | tickets_schedule_id_foreign       | 4       | NULL                       |    3 |   100.00 | Using index; Using temporary; Using filesort |
|  1 | SIMPLE      | schedules       | NULL       | eq_ref | PRIMARY,schedules_film_id_foreign,schedules_room_id_foreign | PRIMARY                           | 4       | cinema.tickets.schedule_id |    1 |    10.00 | Using where                                  |
|  1 | SIMPLE      | films           | NULL       | eq_ref | PRIMARY                                                     | PRIMARY                           | 4       | cinema.schedules.film_id   |    1 |    10.00 | Using where                                  |
|  1 | SIMPLE      | rooms           | NULL       | eq_ref | PRIMARY                                                     | PRIMARY                           | 4       | cinema.schedules.room_id   |    1 |   100.00 | NULL                                         |
|  1 | SIMPLE      | booking_details | NULL       | ref    | booking_details_ticket_id_foreign                           | booking_details_ticket_id_foreign | 4       | cinema.tickets.id          |    2 |   100.00 | NULL                                         |
+----+-------------+-----------------+------------+--------+-------------------------------------------------------------+-----------------------------------+---------+----------------------------+------+----------+----------------------------------------------+
5 rows in set, 1 warning (0.01 sec)
```

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-08-08 04:15 UTC, at-namtran commented on resources/views/admin/pages/schedules/index.blade.php
> +                  <button class="btn btn-danger" onclick="return confirm('@lang('user.admin.message.del')')" type="submit"><i class="fa fa-trash-o  fa-fw" ></i></button>
Nên làm riêng file js để xử lý thay vì dùng confirm

2018-08-08 08:51 UTC, ghost requested changes

2018-08-09 02:31 UTC, ghost requested changes

2018-08-09 02:31 UTC, at-huenguyen commented on app/Http/Controllers/Admin/ScheduleController.php
> +            ];
`]` em nên để lùi lại 4 space nữa

2018-08-09 02:31 UTC, at-huenguyen commented on app/Http/Controllers/Admin/ScheduleController.php
> +            'films.name as fname',
ko nên để `fname` nha em, em để `film_name` lun

2018-08-09 02:31 UTC, at-huenguyen commented on app/Http/Controllers/Admin/ScheduleController.php
> +            DB::raw('COUNT(booking_details.seat_id) as numSeatBooked')
biến này thì em nên để kiểu `num_booked_seat`

2018-08-09 03:00 UTC, at-namtran commented on resources/views/admin/layout/sidebar.blade.php
> +        <a class="app-menu__item" href="#" data-toggle="treeview"><i class="app-menu__icon fa fa-edit"></i>
class chỗ ni của tác giả có liên quan đến file css với js nữa chị, em sẽ sửa ở PR riêng cũng được chị.

2018-08-10 03:14 UTC, ghost approved these changes
LGTM

2018-08-10 08:07 UTC, merged