show list, detail bookings and delete booking
AT-PHPIntership/booking-ticket pull request #35
Opened 2018-08-08 03:22 UTC by at-namtran

## Description
show list show detail and delete booking
## Reference Requirements

## Reference Isuees

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
```sql
explain select count(*) as aggregate from `bookings` 
inner join `users` on `users`.`id` = `bookings`.`user_id` 
inner join `booking_details` on `bookings`.`id` = `booking_details`.`booking_id` 
inner join `tickets` on `tickets`.`id` = `booking_details`.`ticket_id` 
where `bookings`.`deleted_at` is null group by `booking_details`.`booking_id`
```

- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)
![image](https://user-images.githubusercontent.com/40162647/43814468-be238c36-9af4-11e8-952b-d98f63085f26.png)

2018-08-09 07:53 UTC, ghost requested changes

2018-08-09 07:53 UTC, at-huenguyen commented on app/Http/Controllers/Admin/BookingController.php
> +            return view('admin.pages.bookings.show', compact('bookings'));
lùi lại 4 spaces em

2018-08-09 07:53 UTC, at-huenguyen commented on app/Http/Controllers/Admin/BookingController.php
> +    public function destroy($id)
tham khảo [Route Model Binding](https://laravel.com/docs/5.6/routing#route-model-binding) rồi áp dụng thử em

2018-08-09 07:53 UTC, at-huenguyen commented on resources/views/admin/layout/sidebar.blade.php
> +          <span class="app-menu__label">@lang('master.bookings')</span><i class="treeview-indicator fa fa-angle-right"></i>
mấy tên class kiểu này `app-menu__label` có `__` là sao hè?

2018-08-09 07:53 UTC, at-huenguyen commented on resources/views/admin/pages/bookings/index.blade.php
> +        </tbody>
nếu ko có `booking` nào cả thì hiện gì em?

2018-08-09 07:53 UTC, at-huenguyen commented on resources/views/admin/pages/bookings/show.blade.php
> +              <input class="form-control col-md-8" value="{{$bookings[0]->name}}" disabled type="text" >
ở controller em nên dùng `first()`, để ko phải dùng kiểu `$bookings[0]` mà thực ra chỉ có 1 đối tượng

2018-08-09 09:55 UTC, at-namtran commented on resources/views/admin/layout/sidebar.blade.php
> +          <span class="app-menu__label">@lang('master.bookings')</span><i class="treeview-indicator fa fa-angle-right"></i>
ở đây là class `app-menu` dùng chung còn mấy `__label` ` __icon` là chỉ đích danh cụ thể. Do template em dùng của họ nên sử dụng luôn. Em sẽ thay đổi trong PR khác ạ

2018-08-10 03:05 UTC, ghost approved these changes
LGTM

2018-08-10 03:08 UTC, merged