[API] Register User
AT-PHPIntership/booking-ticket pull request #48
Opened 2018-08-16 04:18 UTC by at-khanhnguyen

## Description
Create api register for user.
## Reference Requirements
- Task ID: TI-1

## Reference Isuees
#{issue_id}

## Migrations
NO

## Impacted Areas in Application
List general components of the application that this PR will affect:

-

## SQL query and `explain`
NO query.
- Refer to [Using Explain with MySQL](https://viblo.asia/p/su-dung-explain-de-toi-uu-cau-lenh-mysql-BYjv44gmvxpV)

2018-08-16 07:01 UTC, mvn-namtran-dn reviewed
LGTM

2018-08-17 08:53 UTC, ghost requested changes

2018-08-17 08:53 UTC, at-huenguyen commented on app/Http/Controllers/Api/User/RegisterController.php
> +            $data['user'] = User::find($user->id);
tạo ở trên thì lâý lun chứ `find` làm gì nưã em, tốn câu lệnh

2018-08-17 08:53 UTC, at-huenguyen commented on app/Http/Controllers/Api/User/RegisterController.php
> +        if ($user) {
em dùng `try catch`, nếu tạo user `fail` thì trả lỗi về

2018-08-17 09:10 UTC, at-khanhnguyen commented on app/Http/Controllers/Api/User/RegisterController.php
> +            $data['user'] = User::find($user->id);
Nếu như dùng luôn cái `$user` đã tạo thì nó chỉ chứa thông tin đã được thêm vào `user` chứ nó không chứa mấy trường mình set mặc định trong database chị ạ.

2018-08-17 09:37 UTC, at-huenguyen commented on app/Http/Controllers/Api/User/RegisterController.php
> +            $data['user'] = User::find($user->id);
ok em

2018-08-17 10:21 UTC, ghost approved these changes

2018-08-17 10:21 UTC, merged